// This file is auto-generated by @hey-api/openapi-ts

export const DirItemSchema = {
    properties: {
        is_dir: {
            type: 'boolean',
            title: 'Is Dir'
        },
        path: {
            type: 'string',
            title: 'Path'
        },
        mime: {
            type: 'string',
            title: 'Mime'
        }
    },
    type: 'object',
    required: ['is_dir', 'path', 'mime'],
    title: 'DirItem'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemInfoSchema = {
    properties: {
        current: {
            items: {
                '$ref': '#/components/schemas/DirItem'
            },
            type: 'array',
            title: 'Current'
        },
        parent: {
            items: {
                '$ref': '#/components/schemas/DirItem'
            },
            type: 'array',
            title: 'Parent'
        },
        is_dir: {
            type: 'boolean',
            title: 'Is Dir'
        },
        preview: {
            items: {
                '$ref': '#/components/schemas/DirItem'
            },
            type: 'array',
            title: 'Preview'
        }
    },
    type: 'object',
    required: ['current', 'parent', 'is_dir', 'preview'],
    title: 'ItemInfo'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;