// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type { ItemItemGetData, ItemItemGetError, ItemItemGetResponse, FileFileGetData, FileFileGetError, FileFileGetResponse, ThumbnailThumbnailGetData, ThumbnailThumbnailGetError, ThumbnailThumbnailGetResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Item
 */
export const itemItemGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ItemItemGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ItemItemGetResponse, ItemItemGetError, ThrowOnError>({
        ...options,
        url: '/item'
    });
};

/**
 * File
 */
export const fileFileGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<FileFileGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<FileFileGetResponse, FileFileGetError, ThrowOnError>({
        ...options,
        url: '/file'
    });
};

/**
 * Thumbnail
 */
export const thumbnailThumbnailGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ThumbnailThumbnailGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ThumbnailThumbnailGetResponse, ThumbnailThumbnailGetError, ThrowOnError>({
        ...options,
        url: '/thumbnail'
    });
};