// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type { ItemItemGetData, ItemItemGetError, ItemItemGetResponse, FileFileFilePathGetData, FileFileFilePathGetError, FileFileFilePathGetResponse, ThumbnailThumbnailFilePathGetData, ThumbnailThumbnailFilePathGetError, ThumbnailThumbnailFilePathGetResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Item
 */
export const itemItemGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ItemItemGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ItemItemGetResponse, ItemItemGetError, ThrowOnError>({
        ...options,
        url: '/item'
    });
};

/**
 * File
 */
export const fileFileFilePathGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<FileFileFilePathGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<FileFileFilePathGetResponse, FileFileFilePathGetError, ThrowOnError>({
        ...options,
        url: '/file/{file_path}'
    });
};

/**
 * Thumbnail
 */
export const thumbnailThumbnailFilePathGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ThumbnailThumbnailFilePathGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ThumbnailThumbnailFilePathGetResponse, ThumbnailThumbnailFilePathGetError, ThrowOnError>({
        ...options,
        url: '/thumbnail/{file_path}'
    });
};