// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { FileFilePathGetData, FileFilePathGetError, FileFilePathGetResponse, ItemItemGetData, ItemItemGetError, ItemItemGetResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * File
 */
export const fileFilePathGet = <ThrowOnError extends boolean = false>(options: Options<FileFilePathGetData, ThrowOnError>) => { return (options?.client ?? client).get<FileFilePathGetResponse, FileFilePathGetError, ThrowOnError>({
    ...options,
    url: '/file/{path}'
}); };

/**
 * Item
 */
export const itemItemGet = <ThrowOnError extends boolean = false>(options: Options<ItemItemGetData, ThrowOnError>) => { return (options?.client ?? client).get<ItemItemGetResponse, ItemItemGetError, ThrowOnError>({
    ...options,
    url: '/item'
}); };