// This file is auto-generated by @hey-api/openapi-ts

export type DirItem = {
    is_dir: boolean;
    path: string;
    mime: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemInfo = {
    current: Array<DirItem>;
    parent: Array<DirItem>;
    is_dir: boolean;
    preview: Array<DirItem>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type FileFilePathGetData = {
    path: {
        path: string;
    };
};

export type FileFilePathGetResponse = (unknown);

export type FileFilePathGetError = (HTTPValidationError);

export type ItemItemGetData = {
    query: {
        item: string;
    };
};

export type ItemItemGetResponse = (ItemInfo);

export type ItemItemGetError = (HTTPValidationError);