// This file is auto-generated by @hey-api/openapi-ts

export type DirItem = {
    type: "dir_item";
    path: string;
    mime: string;
    symlink: string;
    stat: (Stat | Error);
};

export type Error = {
    type: "error";
    msg: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemInfo = {
    current: (Array<DirItem> | Error);
    parent: (Array<DirItem> | Error);
    file_info: (DirItem | Error);
    preview: (Array<DirItem> | Error);
};

export type Stat = {
    type: "stat";
    is_dir: boolean;
    time_modified: number;
    size: number;
    user: string;
    group: string;
    permission: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ItemItemGetData = {
    query: {
        item: string;
    };
};

export type ItemItemGetResponse = (ItemInfo);

export type ItemItemGetError = (HTTPValidationError);

export type FileFileGetData = {
    query: {
        path: string;
    };
};

export type FileFileGetResponse = (unknown);

export type FileFileGetError = (HTTPValidationError);

export type ThumbnailThumbnailGetData = {
    query: {
        path: string;
    };
};

export type ThumbnailThumbnailGetResponse = (unknown);

export type ThumbnailThumbnailGetError = (HTTPValidationError);